const mongoose = require("mongoose");

const KynPurchaseSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    // Amount user paid in real money (e.g., $5)
    amountPaid: {
      type: Number,
      required: true,
    },

    // Currency used in payment
    currency: {
      type: String,
      default: "USD",
    },

    // Kyn awarded based on conversion rate
    KynReceived: {
      type: Number,
      required: true,
    },

    // Stripe, Paystack, Flutterwave
    paymentMethod: {
      type: String,
      enum: ["paystack", "stripe", "flutterwave"],
      required: true,
    },

    // Process status: pending, success, failed, refunded
    status: {
      type: String,
      enum: ["pending", "success", "failed", "refunded"],
      default: "pending",
      index: true,
    },

    // Unique payment reference generated by your server or gateway
    reference: {
      type: String,
      required: true,
      unique: true,
    },

    // ID returned by Paystack/Stripe/Flutterwave (e.g., charge ID)
    gatewayTransactionId: {
      type: String,
      index: true,
    },

    // Webhook verification time
    verifiedAt: {
      type: Date,
    },

    // Gateway webhook raw data (for audit + debugging)
    rawData: {
      type: Object,
    },

    // Refund tracking
    refund: {
      refunded: { type: Boolean, default: false },
      refundedAt: { type: Date },
      gatewayRefundId: { type: String },
    },
  },
  {
    timestamps: true, // createdAt, updatedAt
  },
);

module.exports = mongoose.model("KynPurchase", KynPurchaseSchema);
